### ISSUE TITLE
[Bug]: Incompatibility with Budschie's Morph Mod

### ISSUE THREAD

**Issue by davidjjung** [tristankechlo/RandomMobSizes#5] opened 2023-08-15 00:29 UTC
### What happened?

When both of these mods are installed in the same instance, a player morphed into any mob with variable sizes will wig out. More technically speaking, colliding with the side of a block leads to a lot of stuttering (the player is unable to "slide" smoothly against a block while walking into it, as they would normally). It's the equivalent of walking into velcro if you're covered in, well, velcro. Very unpleasant :[ 

Anywho I wasn't sure whose end the issue was on, but given that Budschie hasn't touched their mod in well over a year I figured it was worth mentioning here. Thanks for your time!

### Minecraft Version

1.18.2

### Modversion

randommobsizes-forge-1.18.2-1.3.jar

### Modloader

Forge

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment] 2024-08-22 16:47
Closing this since the issue is quite old, and I could not reproduce the error

**Closed as completed by tristankechlo** 2024-08-22 16:47 UTC
Labels: bug
